site_name: arunsr.in
site_url: https://www.arunsr.in
site_description: This is my site. There are many like it but this one is mine.
site_author: Arun S
docs_dir: home
site_dir: public
repo_url: https://github.com/arunsrin/arunsrin.mkdocs
edit_uri: blob/master/home/
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
        guess_lang: true
theme:
  # name: 'mkdocs'
  name: null
  custom_dir: cinder
  language: 'en'
