site_name: arunsrin's notes
site_url: https://www.arunsr.in
site_description: The truth shall make ye fret.
site_author: Arun S
docs_dir: home
site_dir: public
repo_name: arunsrin.mkdocs
repo_url: https://github.com/arunsrin/arunsrin.mkdocs
edit_uri: blob/master/home/
plugins:
  - search
  - tags:
      tags_allowed:
        - about
        - accounting
        - action
        - adventure
        - advertising
        - ai
        - analysis
        - ansible
        - astronomy
        - atheism
        - automation
        - aws
        - books
        - browsers
        - classics
        - climate
        - cloud
        - coding
        - console
        - containers
        - crypto
        - cyberpunk
        - databases
        - development
        - docker
        - economics
        - editors
        - elastic
        - emacs
        - environment
        - ethics
        - fantasy
        - fiction
        - finance
        - fps
        - free-software
        - games
        - gaming
        - git
        - go
        - grafana
        - grammar
        - health
        - historical
        - history
        - home
        - hub
        - index
        - interactive
        - intro
        - java
        - kafka
        - kubernetes
        - linguistics
        - linux
        - literary
        - literature
        - llm
        - logic
        - math
        - media
        - medicine
        - messaging
        - monitoring
        - movies
        - mystery
        - myth
        - nabokov
        - networking
        - neuroscience
        - non-fiction
        - openssl
        - os
        - packaging
        - people
        - philosophy
        - platformer
        - politics
        - powershell
        - privacy
        - productivity
        - profile
        - programming
        - prometheus
        - psychology
        - puzzle
        - python
        - reading
        - reference
        - research
        - rpg
        - science
        - sci-fi
        - scripting
        - search
        - security
        - shooter
        - sql
        - stoicism
        - story
        - strategy
        - sysadmin
        - systemd
        - tech
        - tips
        - tools
        - tv
        - vcs
        - vim
        - web
        - windows
        - writing
        - wsl
        - xbox
# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
        permalink: true
theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: 'cyan'
      accent: 'light green'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'blue grey'
      accent: 'deep-orange'
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  color_mode: 'auto'
  favicon: 'static/favicon.ico'
  icon:
    logo: material/notebook-edit-outline
    tag:
      id-about: material/account-details
      id-accounting: material/calculator-variant
      id-action: material/sword
      id-adventure: material/map-marker-distance
      id-advertising: material/bullhorn
      id-ai: material/robot
      id-analysis: material/file-search
      id-ansible: simple/ansible
      id-astronomy: material/telescope
      id-atheism: material/creation
      id-automation: material/robot-industrial
      id-aws: fontawesome/brands/aws
      id-books: material/book-open-variant
      id-browsers: material/web
      id-classics: material/view-column
      id-climate: material/thermometer-alert
      id-cloud: material/cloud
      id-coding: material/code-braces
      id-console: material/console-line
      id-containers: material/package-variant
      id-crypto: material/currency-btc
      id-cyberpunk: material/chip
      id-databases: material/database
      id-development: material/xml
      id-docker: simple/docker
      id-economics: material/trending-up
      id-editors: material/laptop
      id-elastic: material/magnify
      id-emacs: simple/gnuemacs
      id-environment: material/leaf
      id-ethics: material/scale-balance
      id-fantasy: material/auto-fix
      id-fiction: material/feather
      id-finance: material/cash-multiple
      id-fps: material/crosshairs-gps
      id-free-software: material/open-source-initiative
      id-games: material/controller-classic
      id-gaming: material/gamepad-variant
      id-git: simple/git
      id-go: simple/go
      id-grafana: material/chart-bell-curve
      id-grammar: material/format-letter-case
      id-health: material/heart-pulse
      id-historical: material/calendar-clock
      id-history: material/history
      id-home: material/home
      id-hub: material/hub
      id-index: material/format-list-bulleted
      id-interactive: material/gesture-tap
      id-intro: material/information-outline
      id-java: fontawesome/brands/java
      id-kafka: material/message-text
      id-kubernetes: material/kubernetes
      id-linguistics: material/translate
      id-linux: material/linux
      id-literary: material/book-open-page-variant
      id-literature: material/library
      id-llm: material/head-dots-horizontal
      id-logic: material/head-lightbulb
      id-math: material/calculator
      id-media: material/multimedia
      id-medicine: material/medical-bag
      id-messaging: material/chat-processing
      id-monitoring: material/chart-line
      id-movies: material/movie-open
      id-mystery: material/magnify-expand
      id-myth: octicons/sparkles-fill-24
      id-nabokov: material/butterfly
      id-networking: material/lan
      id-neuroscience: material/head-cog
      id-non-fiction: material/clipboard-check
      id-openssl: material/shield-lock
      id-os: material/monitor-cellphone
      id-packaging: material/package-variant-closed
      id-people: material/account-group
      id-philosophy: material/thought-bubble
      id-platformer: material/run-fast
      id-politics: material/bank
      id-powershell: material/powershell
      id-privacy: material/incognito
      id-productivity: material/check-circle
      id-profile: material/account-circle
      id-programming: material/code-tags
      id-prometheus: material/fire
      id-psychology: material/brain
      id-puzzle: material/puzzle
      id-python: material/language-python
      id-reading: fontawesome/solid/book-open-reader
      id-reference: material/book-search
      id-research: material/microscope
      id-rpg: material/shield-sword
      id-science: material/flask
      id-sci-fi: material/rocket-launch
      id-scripting: material/script-text-outline
      id-search: material/magnify
      id-security: material/shield-check
      id-shooter: material/target
      id-sql: material/database-search
      id-stoicism: material/head-snowflake
      id-story: material/book-open-variant
      id-strategy: material/chess-knight
      id-sysadmin: material/account-cog
      id-systemd: material/cog-sync
      id-tech: material/laptop
      id-tips: material/lightbulb-on
      id-tools: material/tools
      id-tv: material/television
      id-vcs: material/source-branch
      id-vim: simple/vim
      id-web: material/web
      id-windows: fontawesome/brands/windows
      id-writing: fontawesome/solid/pen-nib
      id-wsl: material/linux
      id-xbox: fontawesome/brands/xbox
  custom_dir: overrides
  language: 'en'
  features:
    # Enhanced navigation
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.footer
    - navigation.expand

    # other enhancements
    - toc.follow
    
    # Content enhancements
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.tooltips
    
    # Search improvements
    - search.suggest
    - search.highlight
extra:
  tags:
    about: id-about
    accounting: id-accounting
    action: id-action
    adventure: id-adventure
    advertising: id-advertising
    ai: id-ai
    analysis: id-analysis
    ansible: id-ansible
    astronomy: id-astronomy
    atheism: id-atheism
    automation: id-automation
    aws: id-aws
    books: id-books
    browsers: id-browsers
    classics: id-classics
    climate: id-climate
    cloud: id-cloud
    coding: id-coding
    console: id-console
    containers: id-containers
    crypto: id-crypto
    cyberpunk: id-cyberpunk
    databases: id-databases
    development: id-development
    docker: id-docker
    economics: id-economics
    editors: id-editors
    elastic: id-elastic
    emacs: id-emacs
    environment: id-environment
    ethics: id-ethics
    fantasy: id-fantasy
    fiction: id-fiction
    finance: id-finance
    fps: id-fps
    free-software: id-free-software
    games: id-games
    gaming: id-gaming
    git: id-git
    go: id-go
    grafana: id-grafana
    grammar: id-grammar
    health: id-health
    historical: id-historical
    history: id-history
    home: id-home
    hub: id-hub
    index: id-index
    interactive: id-interactive
    intro: id-intro
    java: id-java
    kafka: id-kafka
    kubernetes: id-kubernetes
    linguistics: id-linguistics
    linux: id-linux
    literary: id-literary
    literature: id-literature
    llm: id-llm
    logic: id-logic
    math: id-math
    media: id-media
    medicine: id-medicine
    messaging: id-messaging
    monitoring: id-monitoring
    movies: id-movies
    mystery: id-mystery
    myth: id-myth
    nabokov: id-nabokov
    networking: id-networking
    neuroscience: id-neuroscience
    non-fiction: id-non-fiction
    openssl: id-openssl
    os: id-os
    packaging: id-packaging
    people: id-people
    philosophy: id-philosophy
    platformer: id-platformer
    politics: id-politics
    powershell: id-powershell
    privacy: id-privacy
    productivity: id-productivity
    profile: id-profile
    programming: id-programming
    prometheus: id-prometheus
    psychology: id-psychology
    puzzle: id-puzzle
    python: id-python
    reading: id-reading
    reference: id-reference
    research: id-research
    rpg: id-rpg
    science: id-science
    sci-fi: id-sci-fi
    scripting: id-scripting
    search: id-search
    security: id-security
    shooter: id-shooter
    sql: id-sql
    stoicism: id-stoicism
    story: id-story
    strategy: id-strategy
    sysadmin: id-sysadmin
    systemd: id-systemd
    tech: id-tech
    tips: id-tips
    tools: id-tools
    tv: id-tv
    vcs: id-vcs
    vim: id-vim
    web: id-web
    windows: id-windows
    writing: id-writing
    wsl: id-wsl
    xbox: id-xbox
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
extra_javascript:
  - path: static/quotes.js
    defer: true
extra_css:
  - css/extra.css
