site_name: arunsrin's notes
site_url: https://www.arunsr.in
site_description: The truth shall make ye fret.
site_author: Arun S
docs_dir: home
site_dir: public
repo_url: https://github.com/arunsrin/arunsrin.mkdocs
edit_uri: blob/master/home/
plugins:
  - search
  - git-revision-date
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
        guess_lang: true
# extra_css:
#   - "css/mystyle.css"
theme:
  name: 'mkdocs'
  color_mode: 'auto'
  custom_dir: overrides
  user_color_mode_toggle: 'true'
  language: 'en'
  highlightjs: true
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
extra_javascript:
  - js/quotes.json
