site_name: arunsrin's notes
site_url: https://www.arunsr.in
site_description: The truth shall make ye fret.
site_author: Arun S
docs_dir: home
site_dir: public
repo_name: arunsrin.mkdocs
repo_url: https://github.com/arunsrin/arunsrin.mkdocs
edit_uri: blob/master/home/
plugins:
  - search
  - git-revision-date
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
        guess_lang: true
  - toc:
        permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
theme:
  name: 'material'
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: 'cyan'
      accent: 'light green'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: 'blue grey'
      accent: 'deep-orange'
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  color_mode: 'auto'
  favicon: 'static/favicon.ico'
  icon:
    logo: material/notebook-edit-outline
  custom_dir: overrides
  language: 'en'
  highlightjs: true
  features:
    # Enhanced navigation
    - navigation.tracking         # Update URL on scroll
    - navigation.tabs             # Top-level tabs
    - navigation.sections         # Group sections
    - navigation.path             # Breadcrumbs
    - navigation.top              # Back to top button
    - navigation.footer           # Previous/next navigation

    # other enhancements
    - toc.follow                  # sidebar scrolls with the page
    
    # Content enhancements
    - content.code.copy           # Copy code buttons
    - content.action.edit         # Edit page button
    - content.tooltips            # Enhanced tooltips
    
    # Search improvements
    - search.suggest              # Search suggestions
validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
extra_javascript:
  - path: static/quotes.js
    defer: true
extra_css:
  - css/extra.css
