site_name: arunsr.in
site_description: This is my site. There are many like it but this one is mine.
site_author: Arun S
docs_dir: home
site_dir: ../../public
repo_url: https://github.com/arunsrin/arunsrin.mkdocs
edit_uri: blob/master/home/
nav:
        - Home: index.md
        - About: about.md
        - Snippets:
          - 'Docker': snippets/docker.md
          - 'Editors': snippets/editors.md
          - 'Git': snippets/git.md
          - 'Java': snippets/java.md
          - 'Linux': snippets/linux.md
          - 'Networking': snippets/networking.md
          - 'OpenSSL': snippets/openssl.md
          - 'Programming': snippets/programming.md
          - 'Security': snippets/security.md
        - Book Notes:
          - 'Crypto 101': books/crypto101.md
          - 'We are our brains': books/we-are-our-brains.md
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
        guess_lang: true
theme:
  name: 'mkdocs'
  language: 'en'
  favicon: 'img/favicon.ico'
