site_name: arunsrin's notes
site_url: https://notes.arunsr.in
site_description: The truth shall make ye fret.
site_author: Arun S
docs_dir: home
site_dir: public
repo_url: https://github.com/arunsrin/arunsrin.mkdocs
edit_uri: blob/master/home/
plugins:
  - search
  - git-revision-date:
      as_datetime: true
# Extensions
markdown_extensions:
  - admonition
  - codehilite:
        guess_lang: true
theme:
  # name: 'mkdocs'
  name: null
  custom_dir: cinder
  language: 'en'
  highlightjs: true
  colorscheme: solarized-light
