name: Build & Publish

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        check-latest: true
        cache: 'pip'
    - run: pip install -r requirements.txt
    - name: Build
      run: |
        mkdocs build
