name: Build & Publish

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.10
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Build
      run: |
        mkdocs build
    - name: SCP Files
      uses: appleboy/scp-action@master
      env:
          HOST: ssh.phx.nearlyfreespeech.net
          USERNAME: ${{ secrets.USERNAME }}
          PORT: 22
          KEY: ${{ secrets.KEY }}
      with:
        source:  "./public/*"
        target: "/home/public"
        strip_components: 1
        tar_tmp_path: "/home/tmp"
